### ISSUE TITLE
'User' object has no attribute 'has_module_perms'

### ISSUE THREAD

**Issue by shahabaz** [osantana/quickstartup#38]
I tried to login via admin page the login worked fine but after that, I started to get this error User Object has no attribute has_module_perms error. How do I fix this?

I am using the same version provided in production.txt file for the apps

Environment:
Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 3.0.4
Python Version: 3.8.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'widget_tweaks',
 'djmail',
 'quickstartup.qs_core',
 'quickstartup.qs_accounts',
 'quickstartup.qs_pages',
 'quickstartup.qs_contacts',
 'apps.sample']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.gzip.GZipMiddleware',
 'quickstartup.qs_pages.middleware.website_page_middleware']

Traceback (most recent call last):
  File "F:\SAAS\38venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\SAAS\38venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\SAAS\38venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\sites.py", line 499, in index
    app_list = self.get_app_list(request)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\sites.py", line 482, in get_app_list
    app_dict = self._build_app_dict(request)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\sites.py", line 427, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "F:\SAAS\38venv\lib\site-packages\django\contrib\admin\options.py", line 539, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "F:\SAAS\38venv\lib\site-packages\django\utils\functional.py", line 225, in inner
    return func(self._wrapped, *args)

Exception Type: AttributeError at /admin/
Exception Value: 'User' object has no attribute 'has_module_perms'

**Comment by osantana** [comment]
Fix released on 0.16.2
